OShop.Web/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using OShop.Data.Abstract;


namespace OShop.Web.Controllers
{
    public class NavController : Controller
    {
        private readonly IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        // Returns a PartialView with a list of all categories [string] with at least one product.
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
           
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category.Name)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

OShop.Web/Controllers/ShoppingCartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using OShop.Logic.Order.ViewModels;
using OShop.Logic.Shop;
using OShop.Logic.Cart;
using OShop.Logic.Order;
using OShop.Data.Abstract;
using OShop.Order.Abstract;

namespace OShop.Web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IProductRepository productRepository;
        private ICustomerRepository customerRepository;
        private IOrderProcessor orderProcessor;

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public ShoppingCartController (IProductRepository productRepo, ICustomerRepository customerRepo, IOrderProcessor processor)
        {
            productRepository = productRepo;
            customerRepository = customerRepo;
            orderProcessor = processor;
        }


        // GET: ShoppingCart
        public ActionResult Index(ShoppingCart cart, string returnUrl = "/")
        {
            var viewModel = new ShoppingCartViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            };
            return View(viewModel);
        }

        // Adds to cart
        [HttpPost]
        public RedirectToRouteResult AddToCart(ShoppingCart cart, int ProductId, int qty, string returnUrl)
        {
            Product product = productRepository.Products
                .FirstOrDefault(p => p.ProductId == ProductId);

            if (product != null)
            {
                cart.AddToCart(product, qty);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        // Returns a PartialView with total number of items and the total amount of the cart.
        public PartialViewResult CartSummary(ShoppingCart cart)
        {
            return PartialView(cart);
        }

        // Returns a PartialView with the cart's content.
        public PartialViewResult LargeCartSummary(ShoppingCart cart)
        {
            return PartialView(cart);
        }


        // GET: ShoppingCart/Checkout 
        public ActionResult Checkout(ShoppingCart cart, string returnUrl)
        {
            if (cart.IsEmpty)
            {
                return RedirectToAction("Index");
            }
            CustomerViewModel model = new CustomerViewModel();

            // If there is a Customer object in Session, send content to ViewModel
            if (Session["Customer"] != null)
            {
                Customer customer = (Customer)Session["Customer"];
                customer.ToCustomerViewModel(model);
            }
            return View(model);
        }

        // POST: ShoppingCart/Checkout
        // Saves custom details to session and redirect to Payment. 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout(ShoppingCart cart, CustomerViewModel customerViewModel)
        {
            if (ModelState.IsValid)
            {
                Customer customer = customerViewModel.ToCustomer();
                Session["customer"] = customer;

                return RedirectToAction("Payment");
            }

            return View(customerViewModel);
        }

        // GET: ShoppingCart/Payment
        // Displays cart content and customer/address details.
        public ActionResult Payment(ShoppingCart cart)
        {
            PaymentViewModel model = new PaymentViewModel()
            {
                Cart = cart,
                Customer = (Customer)Session["customer"]
            };

            return View(model);
        }
        
        // GET: ShoppingCart/OrderSubmitted
        public ActionResult OrderSubmitted(ShoppingCart cart)
        {
            Customer customer = (Customer)Session["customer"];
            if(cart.IsEmpty || customer == null)
            {
                return RedirectToAction("index");
            }

            int orderStatus = orderProcessor.ProcessOrder(cart, customer);
            
            if(orderStatus < 0)
            {
                return RedirectToAction("OrderRejected");
            }

            Session["Customer"] = null;
            return View();
        }

        public ActionResult OrderRejected()
        {
            return View();
        }

    }
}

OShop.Web/Views/Shared/ProductSummary.cshtml
@model OShop.Logic.Shop.ViewModels.ProductDisplayViewModel
@using OShop.Web.HtmlHelpers;

<div class="col-sm-4">
    <div class="product-container">

        <h5>@Html.DisplayFor(modelItem => Model.CategoryName)</h5>
        <img src="~/Content/Images/Products/@(Model.ImageName)" style="max-width: 200px;">
        <h3>@Html.DisplayFor(modelItem => Model.Name)</h3>
        <p>@Html.FormatAmount(Model.Price)</p>
        @using (Html.BeginForm("AddToCart", "ShoppingCart", FormMethod.Post,
            new { @class = "form-inline" }))
        {
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

            <div class="form-group row">
                <select class="form-control" name="qty">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                </select>

                <button type="submit" class="btn btn-info">
                    <span class="glyphicon glyphicon-shopping-cart"></span> Lägg i korgen
                </button>
            </div>

        }
    </div>
</div>

OShop.Web/Views/Shared/_AdmLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <img src="~/Content/Images/logo.png" />
            <nav>
                <ul>
                    <li><a href="~/Adm">Artiklar</a></li>
                    <li><a href="~/Adm/Orders">Orders</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>


OShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <a href="~/"><img src="~/Content/Images/logo.png" /></a>
            @Html.Action("CartSummary","ShoppingCart")
        </div>
    </div>
    <div class="container">
        <div class="row panel">
            <div class="col-xs-3">

                @Html.Action("Menu","Nav")
            </div>
            <div class="col-xs-8">
                @RenderBody()
            </div>

        </div>
        
        <footer>
            <p>&copy; @DateTime.Now.Year - O-Shopen</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OShop.Web/Views/Shared/_LayoutWithoutCartSummary.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            
                <a href="~/"><img src="~/Content/Images/logo.png"/></a>
        </div>
    </div>
    <div class="container">
        <div class="row panel">

            <div class="col-xs-8">
                @RenderBody()
            </div>
            <div class="col-xs-3">

               
            </div>
        </div>
        
        <footer>
            <p>&copy; @DateTime.Now.Year - O-Shopen</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>